### ISSUE TITLE
Allow Passing `GHU_TOKEN` in HTTP Request

### ISSUE THREAD

**Issue by PeronGH** [smark-d/copilot2chat#5]
In OpenAI API, there is a header for API Key, I think it would be good if `copilot2chat` also allows passing `GHU_TOKEN` as API Key in headers instead of as environment variables.

**Comment by smark-d** [comment]
A server should ideally only use one `GHU_TOKEN`. If multiple are used, it may lead to account suspension. Additionally, if you want to use this API in a third-party application, the API_KEY can be filled with any string.

**Comment by PeronGH** [comment]
Thank you for explanation. Actually I wanted it to have some sort of authentication. If passing `GHU_TOKEN` as API Key is infeasible, can there be an env to set `API_KEY` used for authentication?

**Comment by smark-d** [comment]
you can use this project  https://github.com/songquanpeng/one-api

**Comment by PeronGH** [comment]
OK. Thank you.
